"""
This module provides functions to visualize and extract correlation information from DataFrames.

Functions:
- cor_heatmap(df): 
Plot a heatmap of correlation matrix of a DataFrame.

- most_correlated(df, target_column, k=20): 
Return the most correlated k features with a target column in DataFrame.

- view_correlations(df, columns): 
Return correlation matrix for selected columns in a DataFrame.
    
- most_related_heatmap(correlations, most_related_columns): 
Plot heatmap of most related columns based on correlation matrix.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.special import boxcox1p

def cor_heatmap(df):
    """Plot a heatmap of correlation matrix of a DataFrame

    Args:
        df (pandas dataframe): DataFrame to plot correlation heatmap

    Returns:
        A correlation heatmap generated by seaborn package.
        The darker the color, the higher the relevance.
        The blue stands for positive correlation, the red stands for negative correlation.
    """
    plt.figure(figsize=(20,20))
    corrmat=df.corr()
    sns.heatmap(corrmat,cmap='RdBu',vmin=-0.6,vmax=0.6)

class Feature():

    def __init__(self,df,target_column,k=20):
        self.df = df
        self.target_column = target_column
        self.k = k

    def most_correlated(self):
        """Return the most correlated k features 
        
        Args:
            df (pandas.DataFrame): DataFrame to extract
            target_column (str): prediction or target column name
            k (int): number of correlated features to return
            
        Returns:
            list: list of correlated feature names

        Returns:
            A correlation heatmap generated by seaborn package
        """
        cols = self.df.corr().nlargest(self.k+1, self.target_column)[self.target_column].index
        return cols

    def feature_list(self):
        feature_list = list(self.most_correlated())
        feature_list.remove(self.target_column)
        return feature_list

    def view_correlations(self):
        """Return correlation matrix for selected columns in a DataFrame
        
        Args:
            df (pandas.DataFrame): DataFrame to extract correlation matrix
            columns (list of str): list of column names to view correlations
            
        Returns:
            pandas.DataFrame: correlation matrix of selected columns
        """
        columns = self.most_correlated()
        return self.df[columns].corr()

    def most_related_heatmap(self):
        """Plot heatmap of most related columns based on correlation matrix
        
        Args:
            correlations (pandas.DataFrame): correlation matrix
            most_related_columns (list of str): list of most related column names
            
        Returns:
            A correlation heatmap generated by seaborn package
        """
        plt.subplots(figsize=(10,8))
        correlations = self.view_correlations()
        most_related_columns = self.most_correlated()
        sns.heatmap(correlations, cbar=True, 
                        annot=True, 
                        square=True, 
                        cmap = 'Blues',
                        fmt='.2f',
                        vmin = 0,
                        vmax = 0.8,
                        annot_kws={'size': 10}, 
                        yticklabels=most_related_columns.values, xticklabels=most_related_columns.values)
